// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPLZLgKm-U52AW0PAQJdvWlaQyBaqopYU',
    appId: '1:556768373926:web:048fa46c759f49a2695867',
    messagingSenderId: '556768373926',
    projectId: 'news-wave-8a3c8',
    authDomain: 'news-wave-8a3c8.firebaseapp.com',
    storageBucket: 'news-wave-8a3c8.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCUFQYY7iPiGgQgTYF6L9W_h5xL1naX_V8',
    appId: '1:556768373926:android:619cde32d4a324a3695867',
    messagingSenderId: '556768373926',
    projectId: 'news-wave-8a3c8',
    storageBucket: 'news-wave-8a3c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUHZspoLGRXbOt4gqbyMM9PFNSD9csZkE',
    appId: '1:556768373926:ios:bf9258ceacb0fe94695867',
    messagingSenderId: '556768373926',
    projectId: 'news-wave-8a3c8',
    storageBucket: 'news-wave-8a3c8.appspot.com',
    iosBundleId: 'com.example.newsWave',
  );
}
